import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./Navbar";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" data-theme="dracula">
      <body className={inter.className}>
        <Navbar />
        <main className="px-5">
          <Suspense
            fallback={
              <p>
                <span className="loading loading-spinner loading-lg" />
              </p>
            }
          >
            {children}
          </Suspense>
        </main>
      </body>
    </html>
  );
}
